from Infinite_Dihedral_Quotient import *

write_QHS(INITIAL_HAKEN_FILE)
write_QHS_Dihedral_data(HAKEN_QHS_FILE,HAKEN_QHS_DIHEDRAL_FILE)
write_double_cover_test(HAKEN_QHS_DIHEDRAL_FILE)
search_homomorphism(HAKEN_QHS_DIHEDRAL_FILE)
